services:
  rtc-audio-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - recordings:/app/recordings
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - TRANSCRIBER_MODEL_NAME=${TRANSCRIBER_MODEL_NAME}
      - RECORDINGS_DIR=${RECORDINGS_DIR}
      - CHAT_UPSTREAM_READ_TIMEOUT=${CHAT_UPSTREAM_READ_TIMEOUT}
      - VOICE_MODEL_NAME=${VOICE_MODEL_NAME}
    env_file:
      - .env
    networks:
      - agent-network

volumes:
  recordings:
networks:
  agent-network:
    external: true